"""add phone

Revision ID: bb995b16e2cd
Revises: cbe0f844650d
Create Date: 2018-07-07 12:13:46.135562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb995b16e2cd'
down_revision = 'cbe0f844650d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_authors', sa.Column('phone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_authors', 'phone')
    # ### end Alembic commands ###
